name: "Editor update"

on:
  push:
    branches: [main]
    paths:
     - 'editor/**'
     - '.github/workflows/editor.yml'

jobs:
  deploy:
    name: Deploy editor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 🛎️
        uses: actions/checkout@v2.3.1

      - name: Build editor 🔧
        run: |
          yarn
          cd editor/ && yarn && cd ..
          sed -i "s/#COMMIT#/`git rev-parse HEAD`/g" editor/src/App.js
          CI=false yarn editor-build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: editor/build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          GIT_CONFIG_NAME: Github Actions
          GIT_CONFIG_EMAIL: actions@github.com

